//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMA.APRZP2019.TextEditorProject.TextEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KMA.APRZP2019.TextEditorProject.TextEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file {0}.
        /// </summary>
        internal static string LoadFileException_Msg {
            get {
                return ResourceManager.GetString("LoadFileException_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file.
        /// </summary>
        internal static string SaveFile_Failed {
            get {
                return ResourceManager.GetString("SaveFile_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the current file?.
        /// </summary>
        internal static string SaveFile_Question {
            get {
                return ResourceManager.GetString("SaveFile_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string SaveFile_Success {
            get {
                return ResourceManager.GetString("SaveFile_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file {0}.
        /// </summary>
        internal static string SaveFileException_Msg {
            get {
                return ResourceManager.GetString("SaveFileException_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get user.{0}Reason: {1}.
        /// </summary>
        internal static string SignIn_FailedToGetUser {
            get {
                return ResourceManager.GetString("SignIn_FailedToGetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect login or password!.
        /// </summary>
        internal static string SignIn_FailedToLogin {
            get {
                return ResourceManager.GetString("SignIn_FailedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate password.{0}Reason: {1}.
        /// </summary>
        internal static string SignIn_FailedToValidatePassword {
            get {
                return ResourceManager.GetString("SignIn_FailedToValidatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address {0} is not valid!.
        /// </summary>
        internal static string SignUp_EmailIsNotValid {
            get {
                return ResourceManager.GetString("SignUp_EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create user.{0}Reason: {1}.
        /// </summary>
        internal static string SignUp_FailedToCreateUser {
            get {
                return ResourceManager.GetString("SignUp_FailedToCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate data.{0}Reason: {1}.
        /// </summary>
        internal static string SignUp_FailedToValidateData {
            get {
                return ResourceManager.GetString("SignUp_FailedToValidateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with login {0} already exists!.
        /// </summary>
        internal static string SignUp_UserAlreadyExists {
            get {
                return ResourceManager.GetString("SignUp_UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully created!.
        /// </summary>
        internal static string SignUp_UserSuccessfulyCreated {
            get {
                return ResourceManager.GetString("SignUp_UserSuccessfulyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save user request to history.
        /// </summary>
        internal static string UserRequest_AddFailed {
            get {
                return ResourceManager.GetString("UserRequest_AddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load history of requests.
        /// </summary>
        internal static string UserRequest_LoadAllFailed {
            get {
                return ResourceManager.GetString("UserRequest_LoadAllFailed", resourceCulture);
            }
        }
    }
}
